### ISSUE TITLE
Questions about adding web caching

### ISSUE THREAD

**Issue by mdrideout** [imsamgarg/firebase_cached_image#1]
I was thinking of adding web caching to your plugin, but wanted to find out why this may not have been implemented already.

I was thinking of altering web_cache_manager.dart to convert the files to base64 for caching in sqflite, and decode from base64 for retrieval... or potentially just using a blob.

I was also thinking of using [dart:indexed_db](https://api.dart.dev/stable/2.18.0/dart-indexed_db/dart-indexed_db-library.html) library for a more native web implementation according to this example, where [video blobs are stored in the IndexedDB](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Client-side_storage#storing_complex_data_%E2%80%94_indexeddb)

Any thoughts on this? Web caching is important for my project. Just wanted to get any ideas or thoughts you may have already had before diving in.

Thanks!

**Comment by imsamgarg** [comment]
Hey!,
Actually, I was also thinking the same and I have also implemented that feature using indexedDB but then I dropped it as the package analyzer (pana) that pub.dev uses marks our package non-null-safety package. But i think they have fixed it.

**Comment by Oliver84** [comment]
are there any updates on this?

**Comment by mdrideout** [comment]
I ended up making a similar cross-platform ImageProvider that uses cross-platform HiveDB to store the blobs locally: https://pub.dev/packages/fireproof_closet 

However, now I'm using [imgproxy](https://imgproxy.net/) as an optimized image intermediary and can use the normal built-in Flutter image caching, and do not need to cache Firebase Storage data anymore.
